feat: Implement coin selection using scoped threads
Bitshala-Incubator/rust-coinselect pull request #33
Opened 2024-07-14 14:02 UTC by BEULAHEVANJALIN

Implemented the coin_select function to find the best result among FIFO, lowest larger, and SRD algorithms using scoped threads.

2024-07-14 14:14 UTC, delcin-raj commented
Fix clippy errors

2024-07-14 15:29 UTC, BEULAHEVANJALIN commented
> Fix clippy errors

Fixed

2024-07-15 06:44 UTC, delcin-raj requested changes
Looks good to merge, but clippy and fmt errors are there.

2024-07-15 06:44 UTC, delcin-raj commented on src/lib.rs
> +    let final_state = Arc::try_unwrap(best_result)
no need to create this variable

2024-07-15 07:53 UTC, delcin-raj approved these changes
Thanks for your contribution.
Looking forward to seeing more in future

2024-07-15 08:44 UTC, merged